apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: dotnet-sample
  namespace: default
spec:
  tag: harbor.tanzuathome.net/tce/kpack-dotnet-sample ## Important: CHANGE ME! Docker Hub would be <your_username>/kpack-dotnet-sample
  serviceAccountName: default
  builder:
    name: default
    kind: ClusterBuilder
  source:
    git:
      url: https://github.com/paketo-buildpacks/samples
      revision: main
    subPath: ./dotnet-core/aspnet
