#@ load("@ytt:data", "data")
apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: dotnet-sample
  namespace: default
spec:
  tag: #@ data.values.registry.tags.prefix + data.values.registry.tags.dotnet_sample
  serviceAccountName: #@ data.values.service.account.name
  builder:
    name: my-builder
    kind: Builder
  source:
    git:
      url: https://github.com/paketo-buildpacks/samples
      revision: main
    subPath: ./dotnet-core/aspnet
