contour:
  envoy:
    service:
      type: ClusterIP
    hostPorts:
      enable: true

knative_serving:
  domain:
    type: real
    name: 127-0-0-1.nip.io

excluded_packages:
  - cartographer-catalog.community.tanzu.vmware.com
  - kpack-dependencies.community.tanzu.vmware.com
