registry:
  server: harbor.tanzuathome.net
  username: admin
  password: Harbor12345
  tags:
    prefix: harbor.tanzuathome.net/tce

    # the following are sensible defaults and do not need to change unless there is a collision
    # with an existing tag in your registry. The tag prefix will be prepended to each tag below
    # to calculate a complete image tag
    cartographer: /cartographer-builds-
    builder: /builder
    spring_pet_clinic: /spring-pet-clinic
    dotnet_sample: /dotnet-sample
  secret:
    name: tce-workshop-registry-secret
service:
  account:
    name: tce-workshop-service-account
